name: Build clio Linux
description: Build clio in build directory
inputs:
  conan_profile:
    description: Conan profile name
    required: true
    default: default
  conan_cache_hit:
    description: Whether conan cache has been downloaded
    required: true
runs:
  using: composite
  steps:
    - name: Get number of threads on Linux
      id: linux_threads
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: echo "num=$(($(nproc) - 2))" >> $GITHUB_OUTPUT
      
    - name: Remove few lines CMake/Settings.cmake
      shell: bash
      run: sed -i "22,29d" CMake/Settings.cmake

    - name: Build Clio
      shell: bash
      env:
        BUILD_OPTION: "${{ inputs.conan_cache_hit == 'true' && 'missing' || '' }}"
        LINT: "${{ runner.os == 'Linux' && 'True' || 'False' }}"
      run: |
        mkdir -p build
        cd build
        threads_num=${{ steps.mac_threads.outputs.num || steps.linux_threads.outputs.num }}
        conan install .. -of . -b $BUILD_OPTION -s build_type=Release --profile gcc11
        cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=build/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release .. 
        cmake --build . --parallel $threads_num
