name: Build Clio
on:
  push:
    branches: [master, release/*, develop]
  pull_request:
    branches: [master, release/*, develop]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

  build_linux:
    name: Build linux
    runs-on: [self-hosted]
    env:
      CCACHE_DIR: /home/xzhao/.ccache
      CONAN_USER_HOME: /home/xzhao
    steps:
      - name: Get Clio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Build Clio
        uses: ./.github/actions/build_clio/xunlinuxbuild.yml
        with:
          conan_cache_hit: ${{ steps.restore_cache.outputs.conan_cache_hit }}
