name: Xun clio build
on:
  schedule:
    - cron:  '30 5,17 * * 1'

jobs:
  build_linux:
    name: Build linux
    runs-on: [self-hosted]
    env:
      CCACHE_DIR: /home/xzhao/.ccache
      CONAN_USER_HOME: /home/xzhao
    steps:
      - name: Get Clio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Build Clio
        uses: ./.github/actions/build_clio/xunlinuxbuild.yml
