name: Xun clio build
on:
  workflow_dispatch:
    inputs:
      release_deploy:
        description: "standard release no build"
        type: choice
        options:
        - "no"
        - "yes"
      branch:
        description: 'Branch'
        type: string
      commit:
        description: 'Commit ID'
        type: string
      release_tag:
        description: 'release tag'
        required: true
        type: string
      environment:
        description: 'evnvironment targeting'
        type: choice
        options:
        - prod
        - perf
        - dev
      clio_config_branch:
        description: 'clio config branch'
        type: string
      clio_config_commit:
        description: 'clio config commit'
  
jobs:
  build_linux:
    name: Build linux
    runs-on: [self-hosted]
    env:
      CCACHE_DIR: /home/xzhao/.ccache
      CONAN_USER_HOME: /home/xzhao
    steps:
      - name: Get Clio
        uses: actions/checkout@v4
        with:
          ref: develop
          
      - name: Build Clio
        uses: ./.github/actions/testbuild

      - name: Deploy Clio 
        run: |
             cd /home/xzhao/deploy
             bash deployclioonly.sh newclioboxes /space/clio/clio/build/clio_server


  build_clio_config:
    name: Build Clio config
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ripple/clio-configs.git
          path: /space/clio-configs
          ref: ${{ github.event.inputs.clio_config_branch ||  github.event.inputs.clio_config_commit }}
          fetch-depth: 0  
